### PR TITLE
Parcel template: Fix title generation (github #66)

### PR DESCRIPTION
**Pull request by ScreamingDev**
See https://github.com/awsmug/shipcloud-for-woocommerce/issues/66#issuecomment-317332147

Details in the commit messages.

Please keep this issue open for further changes in the next versions:

- Translation of API elements needs to be more centralized.

### CODE REVIEW

**Comment by andrecedik** [comment]
Looks good to me for now. 👍 

I think we should do is write in the changelog, that people will have to save their parcel templates again to see the changes. Or do we have the option to migrate the data?

**Comment by ScreamingDev** [comment]
There is a compatibility line for that at some points.
If old structure, then transform to new.

This layer is marked with `@deprecated 2.0.0` where we will apply such data migration.

Checklist for merge:

- [ ] Works fine.
- [ ] Changelog written or not needed
- [ ] No conflict
- [ ] In case of bugfix also merged in other minor versions

(I've added this list as a template and it will work as soon as the template is in the master)

**Comment by andrecedik** [comment]
Not sure what happened, but when I edit a previously defined parcel template it shows me the carrier. When I now select a service and save the template it shows me only the carrier again. The parcel templates overview page then shows me this for this entry:
parceltemplate

**Comment by ScreamingDev** [comment]
This is solved except:

- Preselect the chosen values when entering the edit screen.

We need a merge of all open pull requests against release/1.4 to solve this.

**Pull request merged**
