### PR TITLE
Feature/26 edit shipment

### PR DESCRIPTION
**Pull request by ScreamingDev**
- We now have a object pool / service container.
- We now have a repository to manage shipment updates in WordPress.
- All those have the same data structure as the API (as interface, internal it translates to the old mixed up).

See #26 .

### CODE REVIEW

**Comment by andrecedik** [comment]
I have a shipment with the following data
prepare_shipment_01

After creating a shipment the "house number" is missing from the data.
prepare_shipment_02

The button for creating the shipping label is too long and the input fields have no labels, so the user has no idea what they can enter.
prepare_shipment_03

After creating a shipment the button for deleting it is missing. You can also edit the shipment afterwards, which is not supported by shipcloud because after a label has been created you can't change a shipment anymore.
prepare_shipment_04

The "edit shipment" button is also available for shipments where a label has been created before. This is also not possible due to the same reason mentioned above.

**Comment by andrecedik** [comment]
I'm still having this weird country select bug.

This is the prepared order before editing:
prepared_shipment_before_edit

And when I click on "Edit shipment" I get the following form, where the country of the sender is wrong:
prepared_shipment_while_editing

**Comment by andrecedik** [comment]
Also the "edit shipment" button does not make sense, after creating a shipping label, since shipments at shipcloud can't be edited after creating a label for them.

shipments_with_labels

You should just leave it out.

**Comment by ScreamingDev** [comment]
Why don't you see the street number in the last screen? o,O

**Comment by andrecedik** [comment]
Ok, I've checked the data you've transmitted. When updating the shipment, you don't update the shipping at shipcloud. That's fine if you submit the data when creating the shipping label, but when clicking on the create shipping label button, you only transmit `"create_shipping_label": true` and the id of the shipment and not the new data.

**Comment by andrecedik** [comment]
Hmm, I'm getting the shipment data now, but unfortunately the senders phone number is missing @ScreamingDev 😢

**Comment by ScreamingDev** [comment]
I close this as of the meeting today.
1.5 is released.

**Pull request merged**
