### PR TITLE
Release/1.4 preselect

### PR DESCRIPTION
**Pull request by ScreamingDev**
See https://github.com/awsmug/shipcloud-for-woocommerce/issues/66#issuecomment-317331482

More details are written in each commit message.

### CODE REVIEW

**Comment by andrecedik** [comment]
Ok, `to`and `from` are being transmitted once again. 

I found another 🐛 though it seems:
The shipment description is being transmitted as `other_description`. It should be transmitted as `description` in the root of the json to the api. The package description is correctly transmitted as part of `package` and named `description`.

**Comment by andrecedik** [comment]
Wrong:
```
{
  "from": {
    "first_name": "Claus",
    "last_name": "Fahlbusch",
    "company": "shipcloud GmbH",
    "street": "Mittelweg",
    "street_no": "162",
    "zip_code": "20148",
    "city": "Hamburg",
    "state": "Hamburg",
    "country": "DE"
  },
  "to": {
    "first_name": "Andr\u00e9",
    "last_name": "Cedik",
    "company": "",
    "street": "Stra\u00dfe des 17. Juni",
    "street_no": "152",
    "care_of": "",
    "zip_code": "10623",
    "city": "Berlin",
    "state": "",
    "country": "DE",
    "phone": "+491234567890"
  },
  "package": {
    "width": "20",
    "height": "20",
    "length": "20",
    "weight": "2",
    "description": "Paketbeschreibung",
    "type": "parcel"
  },
  "carrier": "dhl",
  "service": "one_day",
  "other_description": "Versand Beschreibung",
  "reference_number": "Bestellung 31",
  "notification_mail": "andre@shipcloud.io"
}
```

Right:
```
{
  "from": {
    "first_name": "Claus",
    "last_name": "Fahlbusch",
    "company": "shipcloud GmbH",
    "street": "Mittelweg",
    "street_no": "162",
    "zip_code": "20148",
    "city": "Hamburg",
    "state": "Hamburg",
    "country": "DE"
  },
  "to": {
    "first_name": "Andr\u00e9",
    "last_name": "Cedik",
    "company": "",
    "street": "Stra\u00dfe des 17. Juni",
    "street_no": "152",
    "care_of": "",
    "zip_code": "10623",
    "city": "Berlin",
    "state": "",
    "country": "DE",
    "phone": "+491234567890"
  },
  "package": {
    "width": "20",
    "height": "20",
    "length": "20",
    "weight": "2",
    "description": "Paketbeschreibung",
    "type": "parcel"
  },
  "carrier": "dhl",
  "service": "one_day",
  "description": "Versand Beschreibung",
  "reference_number": "Bestellung 31",
  "notification_mail": "andre@shipcloud.io"
}
```

**Comment by andrecedik** [comment]
Also when you're trying to create a batch of shipping labels, the parcel template dropdown is missing:
batch_shipping_labels

And the fix you did for creating a single shipment without sender data doesn't seem to work here because when trying to create shipments from orders without sender data, I'm getting an error because `"from":{"country":"DE"}` gets transmitted instead of leaving this out like in the single shipment create mode.

**Comment by ScreamingDev** [comment]
All solved except

> Also when you're trying to create a batch of shipping labels, the parcel template dropdown is missing

as this is another merge request after the current two are done.

**Comment by andrecedik** [comment]
Ok, this looks good:
```
{
  "to": {
    "first_name": "Andr\u00e9",
    "last_name": "Cedik",
    "company": "",
    "street": "Stra\u00dfe des 17. Juni",
    "street_no": "152",
    "care_of": "",
    "zip_code": "10623",
    "city": "Berlin",
    "state": "",
    "country": "DE",
    "phone": "+491234567890"
  },
  "package": {
    "width": "20",
    "height": "20",
    "length": "20",
    "weight": "2",
    "description": "Package description",
    "type": "parcel"
  },
  "carrier": "dhl",
  "service": "standard",
  "reference_number": "Order 31",
  "notification_mail": "andre@shipcloud.io",
  "description": "Shipment description"
}
```

✅  Description is being transmitted correctly
✅  Batch label creation works again
❕ When I open the orders overview page (`/wp-admin/edit.php?post_type=shop_order`) I still get 2 requests to index the carriers - while having 2 orders with wc status "on hold" and 1 with wc status "processing". Have you found the reason for this?

**Pull request merged**
